# Generated by Django 4.2.16 on 2026-08-18 20:13
"""Добавляет проверки положительного времени и количества."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Создаёт ограничения положительных числовых значений."""

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                check=models.Q(("cooking_time__gte", 1)),
                name="recipe_cooking_time_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 1)),
                name="recipe_ingredient_amount_gte_1",
            ),
        ),
    ]
