# Generated by Django 4.2.16 on 2026-08-19
"""Добавляет короткие коды и верхние пределы числовых полей."""

from string import ascii_letters, digits

import django.core.validators
from django.db import migrations, models

ALPHABET = digits + ascii_letters
MAX_VALUE = 32000
MIN_VALUE = 1


def encode_recipe_id(recipe_id):
    """Кодирует идентификатор рецепта в прежнем формате Base62."""

    encoded = ""
    while recipe_id:
        recipe_id, remainder = divmod(recipe_id, len(ALPHABET))
        encoded = ALPHABET[remainder] + encoded
    return encoded or ALPHABET[0]


def populate_short_codes(apps, schema_editor):
    """Сохраняет прежние короткие ссылки для существующих рецептов."""

    recipe_model = apps.get_model("recipes", "Recipe")
    for recipe in recipe_model.objects.iterator():
        recipe.short_code = encode_recipe_id(recipe.pk)
        recipe.save(update_fields=("short_code",))


def validate_numeric_ranges(apps, schema_editor):
    """Останавливает миграцию при выходе данных за новые пределы."""

    recipe_model = apps.get_model("recipes", "Recipe")
    ingredient_model = apps.get_model("recipes", "RecipeIngredient")
    invalid_recipes = recipe_model.objects.exclude(
        cooking_time__range=(MIN_VALUE, MAX_VALUE)
    ).exists()
    invalid_amounts = ingredient_model.objects.exclude(
        amount__range=(MIN_VALUE, MAX_VALUE)
    ).exists()
    if invalid_recipes or invalid_amounts:
        raise RuntimeError(
            "Время приготовления и количество должны быть от 1 до 32000."
        )


class Migration(migrations.Migration):
    """Изменяет схему рецептов без потери существующих ссылок."""

    dependencies = [
        ("recipes", "0003_recipe_recipe_cooking_time_gte_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="short_code",
            field=models.CharField(
                editable=False,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Короткий код",
            ),
        ),
        migrations.RunPython(
            populate_short_codes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="short_code",
            field=models.CharField(
                editable=False,
                max_length=8,
                unique=True,
                verbose_name="Короткий код",
            ),
        ),
        migrations.RunPython(
            validate_numeric_ranges,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="recipe",
            name="recipe_cooking_time_gte_1",
        ),
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="recipe_ingredient_amount_gte_1",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32000),
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32000),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                check=models.Q(("cooking_time__range", (1, 32000))),
                name="recipe_cooking_time_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__range", (1, 32000))),
                name="recipe_ingredient_amount_valid_range",
            ),
        ),
    ]
